### ISSUE TITLE
Look at effect of increasing MTU of the TUN interface

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/mycelium#102]
Currently MTU is a static 1400 to make sure packets would fit in a single packet of the lower layer. However since we use TCP and Quic, this is not strictly needed since those protocols take care of breaking up packets internally, and we also have a framing protocol for all traffic. As such, we could consider increasing the MTU of the TUN here, with the caveat that future transport implementations (if any), need to be able to handle packets larger than the actual link MTU. We should verify if this allows a significant improvement in performance. If not, we need to consider if the future hassle is worth it to do this.

**Comment by delandtj** [comment]
Looking at it, even Ygg sets it at ffffff O_o

**Comment by LeeSmet** [comment]
The current performance is largely sufficient for the common use case. Additionally, I'd like to keep the MTU of 1400, in case we end up setting up something like UDP transports in #144 . The currently preferred route to continue here would be  #141
