### ISSUE TITLE
the building docs need to mention what to do after executing cargo build

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/mycelium#127]
![Screenshot 2024-02-21 at 1 09 48 PM](https://github.com/threefoldtech/mycelium/assets/110984055/0a7a007a-246f-4c55-a165-8614ff5ea57d)
the docs don't mention what to do after the `cargo build` command

**Comment by delandtj** [comment]
are you serious ? 
if you want that level of documentation, which would **maybe** necessary for someone who never ran a linux box, but as mycelium is today, it's a thing 'by engineers for engineers' ... don't be pedantic here, and if you really want, create a PR with added docs.

**Comment by LeeSmet** [comment]
well, there is nothing left to be done after running `cargo build`. At this point, the binary is available in the default location (unless the user has a specific setup where it is someplace else).
