### ISSUE TITLE
mycelium connection lost and had to restart the binary to restore the connection

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/mycelium#128]
### Description

while using mycelium deployment the machine freezes , and i have to terminate the terminal running the script of the binary
`sudo mycelium --peers tcp://83.231.240.31:9651 quic://185.206.122.71:9651 --tun-name utun9
` and start it again so i can connect to the machine again.

 it should be more stable

env used : devnet
version : 2.3.0-alpha11

**Comment by despiegk** [comment]
I have the same problem
mycelium loses connection all the time, independent of the ssh, ping stops working too
then restart mycelium and we;re good again

**Comment by LeeSmet** [comment]
v0.5.0 improved stability
