### ISSUE TITLE
mycelium messaging sub system which is  mentioned in docs is not working

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/mycelium#129]
### Description

as mentioned in docs it was supporting message subsystem to make communication between machines.
https://github.com/threefoldtech/mycelium/blob/master/docs/message.md

after installing mycelium on the machines and trying to make the machines to contact each others using mycelium address it does not work.

network used : devnet
steps to produce 
- make two machines and install mycelium on them
- try to use commands to send message to the other machine using the address 
- it did not work
<img width="1647" alt="Screenshot 2024-02-20 at 4 01 09 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/caa89ec0-c8b0-4187-b008-136ac749c50f">

even receiving messages commands are not working
<img width="840" alt="Screenshot 2024-02-20 at 4 05 24 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/18482fcc-e7d7-4e92-98c4-4b8895505d86">

**Comment by khaledyoussef24** [comment]
made a couple of deployments and installed mycelium on them the previous sending or receiving does not happen and even tried to send to my laptop which has the binary running but still the command stucks only
<img width="567" alt="Screenshot 2024-03-06 at 1 10 25 PM" src="https://github.com/threefoldtech/mycelium/assets/110984055/81b08f01-2f29-41c7-8fd3-879cb3daae61">
<img width="553" alt="Screenshot 2024-03-06 at 1 10 33 PM" src="https://github.com/threefoldtech/mycelium/assets/110984055/911a2252-b51e-4f9b-9cf3-9c474e805d77">

**Comment by LeeSmet** [comment]
Both nodes must be able to reach eachother, please verify if this is the case by pinging them from one another

**Comment by LeeSmet** [comment]
Closing as the issue is stale
