### ISSUE TITLE
`.cargo/config.toml` breaks native builds

### ISSUE THREAD

**Issue by flokli** [threefoldtech/mycelium#132]
I tried to build mycelium on a native aarch64-linux box. It fails to build, as the linker there is the native linker and does not contain the architecture:

```
   Compiling proc-macro2 v1.0.78
   Compiling libc v0.2.152
   Compiling slab v0.4.9
error: linker `aarch64-linux-gnu-gcc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `slab` (build script) due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `proc-macro2` (build script) due to previous error
error: could not compile `libc` (build script) due to previous error
error: could not compile `libc` (build script) due to previous error
```

Removing `.cargo/config.toml` entirely fixes the build there.

I get we might need some configuration / cross setup somewhere, but according to https://doc.rust-lang.org/cargo/reference/config.html#targettriplear the `ar` option is deprecated and the linker option can be set via `CARGO_TARGET_<triple>_LINKER`. If you only use this to build aarch64 binaries in GH Actions, maybe setting this env var instead might be a less invasive alternative?

**Comment by flokli** [comment]
Digged a bit deeper, https://github.com/taiki-e/upload-rust-binary-action?tab=readme-ov-file#example-workflow-cross-compilation says the GH action uses `cross` for cross compilation, and none of their docs mention the `.cargo/config.toml` is necessary, so maybe it'd just work out of the box there too, without it?

**Comment by LeeSmet** [comment]
Right, it's a bit unfortunate since I don't have an aarch64 platform to test locally on. I'll look into it, if release CI is fine without this then I can move this out (if all else fails the global .cargo/config.toml should be a decent place to put it).

**Comment by LeeSmet** [comment]
So after installing `cross` and removing the `.cargo/config.toml`, building for `aarch64-unknown-linux-musl` succeeds (which is the only target we care about and has a special config entry). I'll remove the config.toml and add some notes in the README

**Comment by flokli** [comment]
Nice, thanks! I assume the `rustflags = ["--cfg", "tokio_unstable"]` is also unneeded and just outdated?

**Comment by LeeSmet** [comment]
Yes, it was previously used so tokio_console could be used for some debugging. I've just removed it in a separate commit

**Comment by flokli** [comment]
Awesome! Can you tag a v0.4.1 containing this? See https://github.com/NixOS/nixpkgs/pull/288956#discussion_r1504514507

**Comment by LeeSmet** [comment]
Yeah, I'm currently going through some other stuff, but it should be there later tonight or tomorrow morning.
