### ISSUE TITLE
HTTP API server stopped working (regression)

### ISSUE THREAD

**Issue by flokli** [threefoldtech/mycelium#140]
Some time between 43c961181a9f91cb53f77a883cbe474844fc9454 (good)and 2bd6d11997df8e7d4d07d090935f7d542b48989e (bad) the API server stopped listening.

Didn't bisect yet.

**Comment by LeeSmet** [comment]
Indeed, didn't notice that yesterday. I'm pretty sure the offending commit is 80bf154

**Comment by LeeSmet** [comment]
I'll create a 0.4.2 release with the fix after CI is done
