### ISSUE TITLE
Cut v0.5.0 release

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/mycelium#196]
This will be a breaking release because of #184

**Comment by flokli** [comment]
Do you plan to do a 0.4.x release before, fixing some of the "route metrics rushing to infinity" issues? Or will this be batched together with this one?

**Comment by LeeSmet** [comment]
No I don't intend to do that. The behavior were some routes have continuously increasing metrics seems to be caused mostly by nodes in the network which are not running the latest version (for instance we have a bunch of them running 0.4.0). The source of this is incorrect parameters being used (notably the hold time for routes used to be longer than the source key hold time), combined with some bugs which have already been fixed(the most notable one being the incorrect source key update fixed in v0.4.5). Additionally, the routes with increasing metrics are actually just routes which are no longer present, otherwise the static 0 metric announcement of the node would keep the metric low.

Some changes are also included which, while technically not breaking, would cause poor behavior with the existing nodes which would not yet be updated. So all in all it seems better to all batch this in a breaking release.

I do hope there is not a need for a breaking release anymore in the future. Apologies if this causes any inconvenience :).

**Comment by LeeSmet** [comment]
Now that the release is available, we'll proceed to upgrade 1 of the public peers in every location to allow for a somewhat smooth transition as the network upgrades. The other peer in each location will be done next week or so.
