### ISSUE TITLE
to many fallback routes

### ISSUE THREAD

**Issue by vanheesmaxime** [threefoldtech/mycelium#2]
there still is an issue with the population of fallback routing table. When a node joins the network and it first receives and update with the 65534 metric, and later with a lower metric (once the metric has been established through Hello and IHU), the entry with metric 65534 correctly gets placed into the fallback (instead of selected) but the route always stays there. Even when a more appropriate fallback route comes in.

**Comment by LeeSmet** [comment]
Fixed in #44
