### ISSUE TITLE
Public node unavailable

### ISSUE THREAD

**Issue by r-vdp** [threefoldtech/mycelium#224]
```
2024-04-28T19:54:58.661Z ERROR mycelium::peer_manager > Couldn't connect to Tcp [2a02:1802:5e:0:8478:51ff:fee2:3331]:9651: No route to host (os error 113)
```

```
$ ping 2a02:1802:5e:0:8478:51ff:fee2:333
PING 2a02:1802:5e:0:8478:51ff:fee2:3331 (2a02:1802:5e:0:8478:51ff:fee2:3331) 56 data bytes
From 2a02:1800:10:1058::15 icmp_seq=1 Destination unreachable: Address unreachable
```

**Comment by flokli** [comment]
Ran into this today as well. It seems mycelium behaves a bit poorly if a nonreachable address is configured as a peer.

**Comment by LeeSmet** [comment]
Yeah it seems the physical node this peer was running on has died, we will replace it (hopefully tomorrow). As for the network behavior, the fact that an unreachable node is configured should not impact the behavior, though we currently are observing some network stability for the public nodes as the network expands. This is currently the main point of attention for improvements.

**Comment by LeeSmet** [comment]
The public node has been restored, additonally some changes were done to the other public nodes, they should be more stable now.
