### ISSUE TITLE
Couldn't start mycelium on my machine 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/mycelium#242]
version 0.5.2
I tried to install Mycelium as mentioned in the [documents](https://manual.grid.tf/documentation/system_administrators/mycelium/installation.html) but i faced `Error: NixError(EBUSY)`. 
![Screenshot from 2024-05-08 17-50-01](https://github.com/threefoldtech/mycelium/assets/62248851/d211dba2-3d71-4d34-9c99-64ecc8ad457d)

**Comment by LeeSmet** [comment]
This error usually means there is already a network device on the system with the same name as the tun interface which is being created (`tun0` by default on linux). You can use the `--tun-name` flag to change the name of the nic created by mycelium
