### ISSUE TITLE
Periodically reduce size of the seqno cache

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/mycelium#291]
While this might need some confirmation to originate from the seqno cache, v0.5.3 seems to consume a lot more memory on the public peers. Do some manual management there after removing items to reduce capacity if applicable.

**Comment by iwanbk** [comment]
> v0.5.3 seems to consume a lot more memory on the public peers

How does the strategy to deploy new mycelium release? Maybe gradually each N hours or X days?

**Comment by LeeSmet** [comment]
We generally deploy most of them at roughly the same time, but that shouldn't impact anything since we want stable memory consumption

**Comment by LeeSmet** [comment]
After some more investigation it seems that it might not (entirely) be seqno cache related.

**Comment by LeeSmet** [comment]
Adding some more debugging made it clear that this is, in fact, not caused by the seqno cache
