### ISSUE TITLE
show log message that myceilum is not working properly if myceilum can not connect to any peer 

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/mycelium#38]
for some reason I provided a peer which was down, so myceilum was not able to send or receive messages while nothing shown in the logs that says no peers available or so, I think this should be communicated to the user to update the peer address or so

**Comment by LeeSmet** [comment]
Not being able to connect to a peer is fine, as a peer might come back later (at which point the system will connect with it). That being said, a log line is now available which will inform the user when a connection is made to a node, so the user can check the logs to see if the system created connections at startup.
