### ISSUE TITLE
myceilum takes a lot of time to be functional

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/mycelium#40]
I tried yesterday with @MarioBassem  we both connected to the same peer and tried to reach each other by sending messages but it takes a lot of time and suddenlly it worked 
I tried the same today it is taking too many time and giving this 
![Screenshot from 2023-11-06 10-40-07](https://github.com/threefoldtech/mycelium/assets/1689456/0fef8af7-48a0-42ac-b87c-4d9c908a2c98)

**Comment by LeeSmet** [comment]
The route acquisition has been completely reworked, and this should now behave much better. PUblic nodes have been updated with latest code (which is probably not compatible with the old) (currently running latest release on the repo).
