### ISSUE TITLE
Windows installer release build fails when extracting wintun

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/mycelium#404]
tar on a zip file is not a great idea it seems

**Comment by scottyeager** [comment]
Turns out the `tar` that ships with Windows actually can handle zip files. I guess these Github runners have some other `tar` installed in its place.

The merged fix doesn't work, see #411 for a [working](https://github.com/scottyeager/mycelium/actions/runs/10565220789/job/29269286878) version.

**Comment by LeeSmet** [comment]
The current flow which includes the merged fix is working correctly (https://github.com/LeeSmet/mycelium/actions/runs/10579302428/job/29311413883). Given #410, I'm assuming that the observed behavior is the result of a partial wintun download

**Comment by scottyeager** [comment]
That looks correct indeed. I had only noticed that unzip was trying to open wintun.zip.zip and wintun.zip.ZIP.
