### ISSUE TITLE
Add mycelium-UI as optional component to windows installar

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/mycelium#406]
This requires that the app is bundled on windows, and a checkbox on the installer should be added to install it

**Comment by maximevanhees** [comment]
Temporarily marked as blocked as other framework will be used to create the UI application and thus things might require other approach.

**Comment by LeeSmet** [comment]
Closing in favor of a dedicated UI with embedded mycelium in threefoldtech/myceliumflutter
