### ISSUE TITLE
Use static linking for Windows binary

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/mycelium#419]
I tested the Windows binary produced by the release workflow within a Windows 10 VM. It simply exits with no output:

![image](https://github.com/user-attachments/assets/425ee188-d167-46fd-83e9-4b1affd00fa3)

Then I made a build inside my local VM and it works. So I began to suspect that the binary produced in the workflow is not portable.

The workflow is using a `windows-latest` runner VM to do the build and package the installer. That means the default toolchain will be `x86_64-pc-windows-msvc` and this does not produce static binaries by default. Following [some advice](https://www.reddit.com/r/rust/comments/7mif9i/how_to_compile_binaries_without_dependencies_on/), I tried two approaches:

1. Set the default toolchain to `gnu` by running `rustup default stable-x86_64-pc-windows-gnu`
2. Keeping `x86_64-pc-windows-msvc` and setting `RUSTFLAGS=-C target-feature=+crt-static` to enable static CRT linkage

Both methods appear to solve the issue in cursory tests. Using `gnu` toolchain also approximately doubled the binary size.

If we prefer the `crt-static` approach, it can also be enabled using a `.cargo/config` file:

> Create a file called .cargo\config in your projects root directory with the following contents:
> ```
> [target.x86_64-pc-windows-msvc]
> rustflags = ["-Ctarget-feature=+crt-static"]
> [target.i686-pc-windows-msvc]
> rustflags = ["-Ctarget-feature=+crt-static"]
> ```

**Comment by maximevanhees** [comment]
@scottyeager 

- Switching to  toolchain `stable-x86_64-pc-windows-gnu` did not work for me, I got errors when compiling the OpenSSL crate. 

I've talked about it with @LeeSmet, and we'll opt for the solution to statically link CRT. I'll update the GitHub release workflow to use `RUSTFLAGS=-C target-feature=+crt-static` when building. 

Additional info:
- When checking the dependencies of `mycelium.exe` after installing it with the installer:
```
Dump of file mycelium.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    bcryptprimitives.dll
    api-ms-win-core-synch-l1-2-0.dll
    kernel32.dll
    ws2_32.dll
    advapi32.dll
    shell32.dll
    ole32.dll
    rpcrt4.dll
    iphlpapi.dll
    bcrypt.dll
    ntdll.dll
    VCRUNTIME140.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
```

- When checking dependencies after enabling static CRT linkage:

```
Dump of file target\debug\mycelium.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    bcryptprimitives.dll
    api-ms-win-core-synch-l1-2-0.dll
    advapi32.dll
    kernel32.dll
    oleaut32.dll
    shell32.dll
    ole32.dll
    iphlpapi.dll
    rpcrt4.dll
    ws2_32.dll
    bcrypt.dll
    ntdll.dll
```

We can thus see that the Microsoft C Runtime library, `VCRUNTIME140.dll` is not a dependency anymore and thus this should solve the problem.

**Comment by scottyeager** [comment]
> * Switching to  toolchain `stable-x86_64-pc-windows-gnu` did not work for me, I got errors when compiling the OpenSSL crate.

I did read about some difficulties with OpenSSL on Windows, but in my experience the Github runner was able to build successfully with nothing more than the rustup command I wrote above.

Anyway, sticking with `crt-static` sounds fine to me.
