### ISSUE TITLE
Can not download windows installer

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/mycelium#431]
whenever i try to download windows installer this shows up 
![image](https://github.com/user-attachments/assets/ddba2583-fe15-48f4-8f26-8857283e73d2)

![image](https://github.com/user-attachments/assets/7796975f-81cf-42d0-bfb6-0d97d45f90ba)
and tried to clone the repo and searched for the installer but did not work.
![image](https://github.com/user-attachments/assets/a144f343-a262-401b-b686-6483ad1b6a39)
and did not found it in the assets also.

and the download windows installer for user who is not signed in to git hub  can not download the installer unless the sign in.

**Comment by LeeSmet** [comment]
There is indeed no windows installer in the latest release because of [this bug](https://github.com/threefoldtech/mycelium/issues/404). This has been fixed an will be available in the next release.
