### ISSUE TITLE
Integrate a quic transport 

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/mycelium#87]
For several reasons:
   - the underlying noise protocol has zero round-trip encryption
   - also, it runs over UDP, which would make life quite simple to hole-punch and have real p2p in many setups
   - I don't think it would be difficult (well, for me it would be, but for a @LeeSmet I figure it'll be a breeze)

**Comment by LeeSmet** [comment]
Some considerations:

- The encryption used is not really that useful as we already provide e2e encryption of data in the overlay. Additionally, we can't expect nodes to obtain a valid certificate signed by a trusted authority. So for now we will just ignore this, and accept __any__ certificate
  - That being said, the presence of this handshake in the transport layer itself opens up the possibility for future extensions. In one case this can possibly be relevant for #86, by including a PSK derivative in the certificate. In that way a private network can be construct relying solely on this property.
- We will just use a single stream, as with tcp.
  - In the future there is a potential extension we could look into to use streams to separate out the data and control streams, where the control stream has a higher priority, to have control packets be processed even in case of congestion.
- Need to look into how congstion is handled in quic. There is no congestion control in the overlay, so we need to make sure we don't blow out the underlay connection and drop most of the packets.

Implementation wise, #90 laid the groundwork to support additional transports. In theory this could be added without furrther breaking changes. Internally, a peer is mostly abstract over the connection already: it creates a Framed on the connection which should only require an `AsyncRead + AsyncWrite` bound. We also have an address in the peer to identify the connection, but this is not used in the protocol and only for logging, so this could be anything. Communicating to and from the router is already handled over channels.

There are 2 routes we can take here: create a trait `Connection`, which is a supertrait of both `AsyncRead` and `AsyncWrite`. The trait can then have a method to fetch the identifying information. The connection is not actually saved but just spawned in a task, so we can make `Peer::new()` generic over `C`, and the compiler should monomorphizize the actual code paths. This leads to no code duplication, but it will require additional changes to enable things like multiple streams to be used inside the trait. The other route is to create a dedicated method for every connection type. This makes it easier to use dedicated features, but leads to code duplication. To be seen what is best in implementation.

**Comment by LeeSmet** [comment]
Quic transport integrated in latest release. Some further improvements can be done once some actual usage data is gathered.
